---
- hosts: localhost
  tasks: 
    # Install All applications:
    - include: packages/brew.yml
    - include: packages/gem.yml
    - include: packages/pip.yml
    - include: packages/npm.yml

    # Configure Tools: 
    - include: tools/git.yml
    - include: tools/vim.yml
    
    - include: fonts.yml
    - include: custom.yml